backend:
  name: github
  repo: ralphfour13/test-decap-app
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: dolynmy5k
    api_key: 418469713398953

collections:
  - name: blog
    label: Blog Posts
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - label: "Sections"
        name: "sections"
        widget: "list"
        summary: "{{fields.type | upper}}: {{fields.title}}"
        types:
          # Hero Section Type
          - name: "hero"
            label: "Hero Section"
            widget: object
            summary: "🚀 Hero: {{fields.title}}"
            fields:
              # - {
              #     label: "Section Title",
              #     name: "title",
              #     widget: "string",
              #     default: "Hero Section",
              #   }
              # - {
              #     label: "Section Type",
              #     name: "type",
              #     widget: "hidden",
              #     default: "hero",
              #   }
              # - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Main Title",
                  name: "hero_section_title",
                  widget: "string",
                  hint: "Large heading for the hero section",
                }
              - {
                  label: "Description",
                  name: "hero_description",
                  widget: "text",
                  hint: "Subtitle or description text",
                }
              # - {
              #     label: "Call to Action",
              #     name: "cta",
              #     widget: "object",
              #     required: false,
              #     fields:
              #       [
              #         {
              #           label: "Button Text",
              #           name: "text",
              #           widget: "string",
              #           required: false,
              #         },
              #         {
              #           label: "Button Link",
              #           name: "link",
              #           widget: "string",
              #           required: false,
              #         },
              #       ],
              #   }
              - {
                  label: "Background Color",
                  name: "bg_color",
                  widget: "color",
                  default: "#1a1a2e",
                  required: false,
                }
              - {
                  label: "Hero Title Text Color",
                  name: "hero_title_color",
                  widget: "color",
                  default: "#ffffff",
                  required: false,
                }
              - {
                  label: "Hero Description Text Color",
                  name: "hero_desc_color",
                  widget: "color",
                  default: "#ffffff",
                  required: false,
                }

          # Content Section Type
          - name: "content"
            label: "Content Section"
            widget: object
            summary: "📝 Content: {{fields.title}}"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  default: "Content Section",
                }
              - {
                  label: "Section Type",
                  name: "type",
                  widget: "hidden",
                  default: "content",
                }
              - {
                  label: "Content",
                  name: "content",
                  widget: "markdown",
                  hint: "Rich text content with markdown support",
                }
              - {
                  label: "Layout Style",
                  name: "layout",
                  widget: "select",
                  options: ["default", "two-column", "centered", "wide"],
                  default: "default",
                  required: false,
                }
              - {
                  label: "Background Color",
                  name: "bg_color",
                  widget: "color",
                  default: "#ffffff",
                  required: false,
                }
              - {
                  label: "Text Color",
                  name: "text_color",
                  widget: "color",
                  default: "#333333",
                  required: false,
                }

          # Gallery Section Type
          - name: "gallery"
            label: "Gallery Section"
            widget: object
            summary: "🖼️ Gallery: {{fields.title}}"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  default: "Gallery Section",
                }
              - {
                  label: "Section Type",
                  name: "type",
                  widget: "hidden",
                  default: "gallery",
                }
              - {
                  label: "Gallery Description",
                  name: "description",
                  widget: "text",
                  required: false,
                  hint: "Optional description for the gallery",
                }
              - {
                  label: "Images",
                  name: "images",
                  widget: "list",
                  summary: "{{fields.alt_text}}",
                  fields:
                    [
                      { label: "Image", name: "src", widget: "image" },
                      {
                        label: "Alt Text",
                        name: "alt_text",
                        widget: "string",
                        hint: "Description for accessibility",
                      },
                      {
                        label: "Caption",
                        name: "caption",
                        widget: "string",
                        required: false,
                      },
                    ],
                }
              - {
                  label: "Gallery Layout",
                  name: "layout",
                  widget: "select",
                  options: ["grid", "masonry", "carousel", "lightbox"],
                  default: "grid",
                  required: false,
                }
              - {
                  label: "Columns",
                  name: "columns",
                  widget: "select",
                  options:
                    [
                      { label: "2 Columns", value: "2" },
                      { label: "3 Columns", value: "3" },
                      { label: "4 Columns", value: "4" },
                    ],
                  default: "3",
                  required: false,
                }
              - {
                  label: "Background Color",
                  name: "bg_color",
                  widget: "color",
                  default: "#f8f9fa",
                  required: false,
                }
              - {
                  label: "Text Color",
                  name: "text_color",
                  widget: "color",
                  default: "#333333",
                  required: false,
                }

          # Contact Section Type
          - name: "contact"
            label: "Contact Section"
            widget: object
            summary: "📞 Contact: {{fields.title}}"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  default: "Contact Section",
                }
              - {
                  label: "Section Type",
                  name: "type",
                  widget: "hidden",
                  default: "contact",
                }
              - {
                  label: "Contact Description",
                  name: "description",
                  widget: "text",
                  required: false,
                }
              - {
                  label: "Contact Information",
                  name: "contact_info",
                  widget: "object",
                  fields:
                    [
                      {
                        label: "Email",
                        name: "email",
                        widget: "string",
                        required: false,
                      },
                      {
                        label: "Phone",
                        name: "phone",
                        widget: "string",
                        required: false,
                      },
                      {
                        label: "Address",
                        name: "address",
                        widget: "text",
                        required: false,
                      },
                      {
                        label: "Social Media",
                        name: "social",
                        widget: "list",
                        required: false,
                        fields:
                          [
                            {
                              label: "Platform",
                              name: "platform",
                              widget: "string",
                            },
                            { label: "URL", name: "url", widget: "string" },
                          ],
                      },
                    ],
                }
              - {
                  label: "Show Contact Form",
                  name: "show_form",
                  widget: "boolean",
                  default: false,
                  required: false,
                }
              - {
                  label: "Form Fields",
                  name: "form_fields",
                  widget: "list",
                  required: false,
                  condition: { field: "show_form", value: true },
                  fields:
                    [
                      { label: "Field Name", name: "name", widget: "string" },
                      {
                        label: "Field Type",
                        name: "type",
                        widget: "select",
                        options: ["text", "email", "tel", "textarea"],
                      },
                      {
                        label: "Required",
                        name: "required",
                        widget: "boolean",
                        default: false,
                      },
                    ],
                }
              - {
                  label: "Background Color",
                  name: "bg_color",
                  widget: "color",
                  default: "#ffffff",
                  required: false,
                }
              - {
                  label: "Text Color",
                  name: "text_color",
                  widget: "color",
                  default: "#333333",
                  required: false,
                }

          # Custom Section Type (Flexible)
          - name: "custom"
            label: "Custom Section"
            widget: object
            summary: "⚙️ Custom: {{fields.title}}"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  default: "Custom Section",
                }
              - {
                  label: "Section Type",
                  name: "type",
                  widget: "hidden",
                  default: "custom",
                }
              - {
                  label: "Custom HTML/Content",
                  name: "content",
                  widget: "code",
                  default_language: "html",
                  hint: "Custom HTML, CSS, or JavaScript code",
                }
              - {
                  label: "Additional CSS",
                  name: "custom_css",
                  widget: "code",
                  default_language: "css",
                  required: false,
                }
              - {
                  label: "Additional JavaScript",
                  name: "custom_js",
                  widget: "code",
                  default_language: "javascript",
                  required: false,
                }
              - {
                  label: "Background Color",
                  name: "bg_color",
                  widget: "color",
                  default: "#ffffff",
                  required: false,
                }
              - {
                  label: "Text Color",
                  name: "text_color",
                  widget: "color",
                  default: "#333333",
                  required: false,
                }

  - name: "pages"
    label: "Pages"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - label: "Sections"
        name: "sections"
        widget: "list"
        summary: "{{fields.type | upper}}: {{fields.title}}"
        types:
          # Hero Section Type
          - name: "hero"
            label: "Hero Section"
            widget: object
            summary: "🚀 Hero: {{fields.title}}"
            fields:
              # - {
              #     label: "Section Title",
              #     name: "title",
              #     widget: "string",
              #     default: "Hero Section",
              #   }
              # - {
              #     label: "Section Type",
              #     name: "type",
              #     widget: "hidden",
              #     default: "hero",
              #   }
              # - { label: "Section Title", name: "title", widget: "string" }
              - {
                  label: "Main Title",
                  name: "hero_section_title",
                  widget: "string",
                  hint: "Large heading for the hero section",
                }
              - {
                  label: "Description",
                  name: "hero_description",
                  widget: "text",
                  hint: "Subtitle or description text",
                  required: false,
                }
              # - {
              #     label: "Call to Action",
              #     name: "cta",
              #     widget: "object",
              #     required: false,
              #     fields:
              #       [
              #         {
              #           label: "Button Text",
              #           name: "text",
              #           widget: "string",
              #           required: false,
              #         },
              #         {
              #           label: "Button Link",
              #           name: "link",
              #           widget: "string",
              #           required: false,
              #         },
              #       ],
              #   }
              - {
                  label: "Background Color",
                  name: "bg_color",
                  widget: "color",
                  default: "#1a1a2e",
                  required: false,
                }
              - {
                  label: "Hero Title Text Color",
                  name: "hero_title_color",
                  widget: "color",
                  default: "#ffffff",
                  required: false,
                }
              - {
                  label: "Hero Description Text Color",
                  name: "hero_desc_color",
                  widget: "color",
                  default: "#ffffff",
                  required: false,
                }
                # Mutli Column Section
          - label: "Multi Column Section"
            name: "multi_column"
            fields:
              - {
                  label: "Background Color",
                  name: "bg_color",
                  widget: "color",
                  default: "#ffffff",
                }
              - label: "Columns"
                name: "columns"
                widget: "list"
                types:
                  - label: "Image Column"
                    name: "image"
                    fields:
                      - { label: "Image", name: "image_url", widget: "image" }
                      - {
                          label: "Alt Text",
                          name: "alt_text",
                          widget: "string",
                        }
                      - {
                          label: "Width",
                          name: "width",
                          widget: "string",
                          default: "600",
                        }
                      - {
                          label: "Height",
                          name: "height",
                          widget: "string",
                          default: "400",
                        }

                  - label: "Content Column"
                    name: "content"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - {
                          label: "Title Highlight",
                          name: "title_highlight",
                          widget: "string",
                          required: false,
                        }
                      - {
                          label: "Highlight Color",
                          name: "title_highlight_color",
                          widget: "color",
                          default: "#8b5cf6",
                        }
                      - {
                          label: "Description",
                          name: "description",
                          widget: "text",
                        }
                      - {
                          label: "Text Align",
                          name: "text_align",
                          widget: "select",
                          options: ["left", "center", "right"],
                          default: "left",
                        }
# site_url: https://clinquant-moxie-14c48f.netlify.app/
# site_id: 66f9fc69-c45d-4e15-b855-1fcb64431a6e
